#!/usr/bin/env python
from sys import stdin, stdout
import os, time, argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
            description='Simple script to run the ascii-video'
    )
    parser.add_argument(
            '-r',
            '--repeat',
            help='--repeat=y/n',
            type=str,
            default='n'
    )
    parser.add_argument(
            '-v',
            '--velocity',
            help='--velocity=2',
            type=float,
            default=1
    )

    arguments = parser.parse_args()
    repeat = arguments.repeat
    vel = arguments.velocity

    info = 'info.txt'
    with open('/home/azz/.scripts/run-video/' + info, 'r') as file:
        fps = float(file.readline()[5:])
        height = int(float(file.readline()[7:]))
        total = float(file.readline())

    x = 0
    sleep_time = 1/(fps * vel)
    video_file = 'video.txt'
    file = open('/home/azz/.scripts/run-video/' + video_file, 'r')
    while x < total:
        output = ""

        for y in range (height):
            output += file.readline()
            
        stdout.write(output)
        time.sleep(sleep_time)
        os.system('cls' if os.name == 'nt' else 'clear')
        x += 1
        if repeat  == 'y' and x == total - 1:
            x = 0
            file.seek(0)
